#!/usr/bin/env bash 

mkdir -p /usr/include/postgresql/internal
mkdir -p /usr/include/postgresql/internal/libpq 
mkdir -p /usr/include/postgresql/libpq
mkdir -p /usr/share/locale/cs/LC_MESSAGES
mkdir -p /usr/share/locale/de/LC_MESSAGES
mkdir -p /usr/share/locale/es/LC_MESSAGES
mkdir -p /usr/share/locale/fr/LC_MESSAGES
mkdir -p /usr/share/locale/it/LC_MESSAGES
mkdir -p /usr/share/locale/ja/LC_MESSAGES
mkdir -p /usr/share/locale/ko/LC_MESSAGES
mkdir -p /usr/share/locale/nb/LC_MESSAGES
mkdir -p /usr/share/locale/pl/LC_MESSAGES
mkdir -p /usr/share/locale/pt_BR/LC_MESSAGES
mkdir -p /usr/share/locale/ro/LC_MESSAGES
mkdir -p /usr/share/locale/ru/LC_MESSAGES
mkdir -p /usr/share/locale/sv/LC_MESSAGES
mkdir -p /usr/share/locale/ta/LC_MESSAGES
mkdir -p /usr/share/locale/tr/LC_MESSAGES
mkdir -p /usr/share/locale/zh_CN/LC_MESSAGES
mkdir -p /usr/share/locale/zh_TW/LC_MESSAGES
mkdir -p /usr/lib/x86_64-linux-gnu/pkgconfig
mkdir -p /usr/share/doc/libpq-dev
mkdir -p /usr/share/man/man1


cp /tmp/pg_config /usr/bin/pg_config
cp /tmp/postgresql/internal/c.h /usr/include/postgresql/internal/c.h
cp /tmp/postgresql/internal/libpq-int.h /usr/include/postgresql/internal/libpq-int.h
cp /tmp/postgresql/internal/pqcomm.h /usr/include/postgresql/internal/libpq/pqcomm.h
cp /tmp/postgresql/internal/port.h /usr/include/postgresql/internal/port.h
cp /tmp/postgresql/internal/postgres_fe.h /usr/include/postgresql/internal/postgres_fe.h
cp /tmp/postgresql/internal/pqexpbuffer.h /usr/include/postgresql/internal/pqexpbuffer.h
cp /tmp/postgresql/libpq-events.h /usr/include/postgresql/libpq-events.h
cp /tmp/postgresql/libpq-fe.h /usr/include/postgresql/libpq-fe.h
cp /tmp/postgresql/libpq-fs.h /usr/include/postgresql/libpq/libpq-fs.h
cp /tmp/postgresql/pg_config.h /usr/include/postgresql/pg_config.h
cp /tmp/postgresql/pg_config_ext.h /usr/include/postgresql/pg_config_ext.h
cp /tmp/postgresql/pg_config_manual.h /usr/include/postgresql/pg_config_manual.h
cp /tmp/postgresql/pg_config_os.h /usr/include/postgresql/pg_config_os.h
cp /tmp/postgresql/postgres_ext.h /usr/include/postgresql/postgres_ext.h
cp /tmp/x86_64-linux-gnu/libpgcommon.a /usr/lib/x86_64-linux-gnu/libpgcommon.a
cp /tmp/x86_64-linux-gnu/libpgfeutils.a /usr/lib/x86_64-linux-gnu/libpgfeutils.a
cp /tmp/x86_64-linux-gnu/libpgport.a /usr/lib/x86_64-linux-gnu/libpgport.a
cp /tmp/x86_64-linux-gnu/libpq.a /usr/lib/x86_64-linux-gnu/libpq.a
cp /tmp/x86_64-linux-gnu/libpq.so /usr/lib/x86_64-linux-gnu/libpq.so
cp /tmp/x86_64-linux-gnu/pkgconfig/libpq.pc /usr/lib/x86_64-linux-gnu/pkgconfig/libpq.pc
cp /tmp/libpq-dev/changelog.Debian.gz /usr/share/doc/libpq-dev/changelog.Debian.gz
cp /tmp/libpq-dev/changelog.gz /usr/share/doc/libpq-dev/changelog.gz
cp /tmp/libpq-dev/copyright /usr/share/doc/libpq-dev/copyright
cp /tmp/LC_MESSAGES/pg_config-9.6.mo /usr/share/locale/cs/LC_MESSAGES/pg_config-9.6.mo
cp /tmp/LC_MESSAGES/pg_config-9.6.mo /usr/share/locale/de/LC_MESSAGES/pg_config-9.6.mo
cp /tmp/LC_MESSAGES/pg_config-9.6.mo /usr/share/locale/es/LC_MESSAGES/pg_config-9.6.mo
cp /tmp/LC_MESSAGES/pg_config-9.6.mo /usr/share/locale/fr/LC_MESSAGES/pg_config-9.6.mo
cp /tmp/LC_MESSAGES/pg_config-9.6.mo /usr/share/locale/it/LC_MESSAGES/pg_config-9.6.mo
cp /tmp/LC_MESSAGES/pg_config-9.6.mo /usr/share/locale/ja/LC_MESSAGES/pg_config-9.6.mo
cp /tmp/LC_MESSAGES/pg_config-9.6.mo /usr/share/locale/ko/LC_MESSAGES/pg_config-9.6.mo
cp /tmp/LC_MESSAGES/pg_config-9.6.mo /usr/share/locale/nb/LC_MESSAGES/pg_config-9.6.mo
cp /tmp/LC_MESSAGES/pg_config-9.6.mo /usr/share/locale/pl/LC_MESSAGES/pg_config-9.6.mo
cp /tmp/LC_MESSAGES/pg_config-9.6.mo /usr/share/locale/pt_BR/LC_MESSAGES/pg_config-9.6.mo
cp /tmp/LC_MESSAGES/pg_config-9.6.mo /usr/share/locale/ro/LC_MESSAGES/pg_config-9.6.mo
cp /tmp/LC_MESSAGES/pg_config-9.6.mo /usr/share/locale/ru/LC_MESSAGES/pg_config-9.6.mo
cp /tmp/LC_MESSAGES/pg_config-9.6.mo /usr/share/locale/sv/LC_MESSAGES/pg_config-9.6.mo
cp /tmp/LC_MESSAGES/pg_config-9.6.mo /usr/share/locale/ta/LC_MESSAGES/pg_config-9.6.mo
cp /tmp/LC_MESSAGES/pg_config-9.6.mo /usr/share/locale/tr/LC_MESSAGES/pg_config-9.6.mo
cp /tmp/LC_MESSAGES/pg_config-9.6.mo /usr/share/locale/zh_CN/LC_MESSAGES/pg_config-9.6.mo
cp /tmp/LC_MESSAGES/pg_config-9.6.mo /usr/share/locale/zh_TW/LC_MESSAGES/pg_config-9.6.mo
cp /tmp/man1/pg_config.1.gz /usr/share/man/man1/pg_config.1.gz