version: '3.7' 

services:  
  php:
    build: './php'
    restart: always
    ports:
      - 8000:80
    networks:
      - backend
      - frontend
    volumes:
      - ./php/testing:/var/www/html
    depends_on:
      - db
  db:
    image: mysql
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Infected42!
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: Infected42!
    networks:
      - backend
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - backend
networks:
  backend:
  frontend:
