version: '3.7' 

services:  
  php:
    build: './php'
    restart: always
    ports:
      - "80:80"
    networks:
      - backend
      - frontend
    volumes:
      - ./php/testing:/var/www/html
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Infected42!
      POSTGRES_USER: testuser
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    networks:
      - backend
networks:
  backend:
  frontend:
